// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYE3ZsmsfdN1UUiJEVvt_Fa6XMt8Poz8',
    appId: '1:795196127433:web:98984880f5e1255a7fb518',
    messagingSenderId: '795196127433',
    projectId: 'school-app-fb969',
    authDomain: 'school-app-fb969.firebaseapp.com',
    storageBucket: 'school-app-fb969.appspot.com',
    measurementId: 'G-R6L0L8C28W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlJtLCt9OvXzw0U9VuIv6zPEaEN4cVeE',
    appId: '1:795196127433:android:e8b4a390ede728b17fb518',
    messagingSenderId: '795196127433',
    projectId: 'school-app-fb969',
    storageBucket: 'school-app-fb969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNACp7flwVH4tznJd0ZhLKqk04hJuQobc',
    appId: '1:795196127433:ios:954a4ae653b8e91c7fb518',
    messagingSenderId: '795196127433',
    projectId: 'school-app-fb969',
    storageBucket: 'school-app-fb969.appspot.com',
    iosBundleId: 'com.example',
  );
}
